Product.find(1).update(stock_quantity: nil)
Product.find(2).update(stock_quantity: 20)
Product.find(3).update(stock_quantity: 30)
Product.find(4).update(stock_quantity: 40)
Product.find(5).update(stock_quantity: 50)
Product.find(6).update(stock_quantity: nil)
